apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: net-tools
spec:
  selector:
    matchLabels:
      component: net-tools
  template:
    metadata:
      labels:
        component: net-tools
    spec:
      containers:
      - image: danielcaldwell/nettools:1.0
        imagePullPolicy: Always
        name: net-tools
        command: ["sleep"]
        args: ["infinity"]
      restartPolicy: Always
